const CourseApi = [
    {
        id: "1",
        title: "Web Development",
        image: require("../../assets/web.webp"),
        description: "Web development refers to the process of creating and maintaining websites or web applications that can be accessed over the internet.",
        course1: "HTML",
        course2: "CSS",
        course3: "Javascript",
        price: "5000",
    },
    {
        id: "2",
        title: "Cloud Computing",
        image: require("../../assets/cloud.png"),
        description: "Web development refers to the process of creating and maintaining websites or web applications that can be accessed over the internet.",
        course1: "HTML",
        course2: "CSS",
        course3: "Javascript",
        price: "5000",
    },
    {
        id: "3",
        title: "Artificial Intelligence",
        image: require("../../assets/AIML.jpg"),
        description: "Web development refers to the process of creating and maintaining websites or web applications that can be accessed over the internet.",
        course1: "HTML",
        course2: "CSS",
        course3: "Javascript",
        price: "5000",
    },
    {
        id: "4",
        title: "Blockchain",
        image: require("../../assets/BlockChain.jpg"),
        description: "Web development refers to the process of creating and maintaining websites or web applications that can be accessed over the internet.",
        course1: "HTML",
        course2: "CSS",
        course3: "Javascript",
        price: "5000",
    },
    {
        id: "5",
        title: "Ethical Hacking",
        image: require("../../assets/photo1.jpg"),
        description: "Web development refers to the process of creating and maintaining websites or web applications that can be accessed over the internet.",
        course1: "HTML",
        course2: "CSS",
        course3: "Javascript",
        price: "5000",
    },
    {
        id: "6",
        title: "MEAN Stack",
        image: require("../../assets/Mean.jpg"),
        description: "Web development refers to the process of creating and maintaining websites or web applications that can be accessed over the internet.",
        course1: "HTML",
        course2: "CSS",
        course3: "Javascript",
        price: "5000",
    },
]

export default CourseApi;